### ISSUE TITLE
Translation record type

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-schema#165]
Rough schema:

```protobuf
message Translation {
  recordType: string // lets say, 'field' or 'role'
  recordId: byte[] // the id that points to the record we want to get a translation for
  fieldRef: string[] // the field from that record that we want to translate the string for
  languageCode: string // BCP-47 or ISO 638-3
  message: string // the actual translated string
 
}
```

**Comment by gmaclennan** [comment]
I did some more research into this today, looking at [IETF BCP-47](https://en.wikipedia.org/wiki/IETF_language_tag) for ideas.

A lot of our partner languages are not in ISO 639-1 (two-letter codes), so we need ISO-639-3, which I think covers most languages we know of. 

There are some cases where regional differences are important, e.g. Latin American Spanish vs. Spain, or British English vs. American English. However it is better to fall back to another regional variant rather than English if a match does not exist.

I don't think the other language subtags in BCP-47 are important / relevant (e.g. extended language, script, variant, extension). We can add support later if needed, and adding scripts would require ensuring fonts with support for that script are included in the app.

The BCP-47 primary language subtag is:

> a two-letter language code from [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) (2002) or a three-letter code from [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) (1998), [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) (2007) or ISO 639-5 (2008), or registered through the BCP 47 process and composed of five to eight letters

We could just use that definition, although it potentially makes matching more complicated. I'm tempted to just use ISO 639-3, but we would still need to ship lookup tables to go from ISO-639-3 to the language reported as a device's locale, which might well be ISO 639-1 (e.g. we could define english translations solely with `eng` (ISO 639-3), but when reading the device language we might only get `en` (ISO 639-1), so we would need to map that to the equivalent ISO 639-3).

So, my suggestion is, initially:

```ts
interface Translation {
  // ... other props from above
  languageCode: string // three letter code from ISO 639-3 defining the language used
  regionCode?: string // a two-letter country code from [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) or a three-digit code from [UN M.49](https://en.wikipedia.org/wiki/UN_M49) for geographical regions
}
```

For `fieldRef`, I've swung back to thinking that this should just be a string, defined using a dot path as in [dot-prop](https://github.com/sindresorhus/dot-prop). That way we can do lookups as:

```sql
SELECT message, regionCode
FROM translations 
WHERE recordType = ${recordType}
  AND recordId = ${recordId}
  AND fieldRef = ${fieldRef}
  AND languageCode = ${languageCode}
```

And if we get more than one row back, can compare region codes to get the preferred one.

We will need code in the app for mapping the app language option to the appropriate ISO 639-3 three-letter code and region (we should probably switch the app language choice to use the same parameters as these translations)
